### ISSUE TITLE
SQLite driver missing in r2rml

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-IDS/data2services-pipeline#21]
Cannot process SQLite db with r2rml because driver are missing

```
2018-12-06 15:16:46 ERROR R2RMLProcessor:98 - Error connecting to database.
java.sql.SQLException: No suitable driver found for jdbc:sqlite:/data/chinook.db
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at r2rml.engine.R2RMLProcessor.createDatabaseConnection(R2RMLProcessor.java:90)
	at r2rml.engine.R2RMLProcessor.execute(R2RMLProcessor.java:39)
	at r2rml.Main.main(Main.java:59)
```

**Comment by vemonet** [comment]
https://github.com/chrdebru/r2rml/issues/5

**Comment by vemonet** [comment]
Fixed, pull request awaiting https://github.com/amalic/r2rml/pull/3
